# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdep',
                'doc_host': 'https://restlessronin.github.io',
                'git_url': 'https://github.com/restlessronin/nbdep',
                'lib_path': 'nbdep'},
  'syms': {'nbdep.core': {'nbdep.core.foo': ('core.html#foo', 'nbdep/core.py')}}}
